import Link from "next/link";
import { DashboardShell } from "@/components/dashboard-shell";
import { ExternalClientForm, InviteExhibitorForm } from "@/components/agency-client-forms";
import { updateAgencyRelationship } from "@/app/actions/agency-clients";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { whatsappUrl } from "@/lib/agency-operations";

export default async function AgencyClientsPage(){
  const profile=await requireRole(["agency"]),db=await createClient(); if(!db) throw new Error("Workspace unavailable.");
  const {data:agency}=await db.from("agencies").select("id").eq("owner_id",profile.id).maybeSingle();
  const [{data:relationships,error},{data:clientProfiles}]=agency?await Promise.all([db.from("agency_exhibitor_relationships").select("id,status,invited_email,created_at,exhibitors(id,company_name,kind,industry,primary_contact_name,contact_phone,contact_email)").eq("agency_id",agency.id).order("created_at",{ascending:false}),db.from("agency_client_profiles").select("exhibitor_id,whatsapp_phone,payment_status").eq("agency_id",agency.id)]):[{data:[],error:null},{data:[]}];
  if(error) throw new Error("Unable to load clients."); const profileMap=new Map((clientProfiles??[]).map(item=>[item.exhibitor_id,item]));
  return <DashboardShell active="agency" current="/dashboard/agency/clients"><h1 className="text-4xl font-black">Clients</h1><p className="mt-2 text-[var(--muted)]">Platform exhibitors and reusable agency-managed client profiles.</p><section className="mt-7 grid gap-5 lg:grid-cols-2"><InviteExhibitorForm/><ExternalClientForm/></section><section className="mt-8"><h2 className="mb-4 text-2xl font-black">Client relationships</h2><div className="grid gap-4 md:grid-cols-2">{relationships?.map(row=>{const client=Array.isArray(row.exhibitors)?row.exhibitors[0]:row.exhibitors,details=client?profileMap.get(client.id):null,wa=whatsappUrl(details?.whatsapp_phone||client?.contact_phone||"");return <article className="panel p-5" key={row.id}><div className="flex items-start justify-between gap-3"><div><span className="badge capitalize">{row.status}</span><h3 className="mt-2 text-xl font-black">{client?.company_name??"Invited client"}</h3><p className="text-sm text-[var(--muted)]">{client?.primary_contact_name||row.invited_email||"Contact pending"}</p></div>{details?.payment_status?<span className="badge capitalize">{details.payment_status.replaceAll("_"," ")}</span>:null}</div>{row.status==="active"&&client?<div className="mt-4 flex flex-wrap gap-2"><Link className="button button-primary" href={`/dashboard/agency/clients/${client.id}`}>Open profile</Link>{client.contact_phone?<a className="button button-secondary" href={`tel:${client.contact_phone}`}>Call</a>:null}{wa?<a className="button button-secondary" href={wa}>WhatsApp</a>:null}{client.contact_email?<a className="button button-secondary" href={`mailto:${client.contact_email}`}>Email</a>:null}</div>:null}{row.status==="pending"?<div className="mt-4 flex gap-2"><form action={updateAgencyRelationship}><input type="hidden" name="relationship_id" value={row.id}/><input type="hidden" name="intent" value="resend"/><button className="button button-secondary">Resend</button></form><form action={updateAgencyRelationship}><input type="hidden" name="relationship_id" value={row.id}/><input type="hidden" name="intent" value="cancel"/><button className="button button-secondary">Cancel</button></form></div>:null}</article>})}{!relationships?.length?<p className="panel p-5">No clients yet.</p>:null}</div></section></DashboardShell>;
}
