import Link from "next/link";
import Image from "next/image";
import {notFound} from "next/navigation";
import {requireExhibitorWorkspace} from "@/lib/dashboard-workspace";
import {updateStallDetails} from "@/app/actions/stalls";
import {SubmitButton} from "@/components/submit-button";

type Role={id:string;title:string;status:string;headcount:number;stall_id:string|null};
export default async function StallDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string}>}){
 const [{id},{entity,db},query]=await Promise.all([params,requireExhibitorWorkspace(),searchParams]);
 const {data:stall,error}=await db.from("exhibitor_stalls").select("*,events(title,venue,city,starts_at,ends_at,verification_status,staffing_roles(id,title,status,headcount,stall_id))").eq("id",id).eq("exhibitor_id",entity.id).maybeSingle();
 if(error)throw new Error("Unable to load stall.");if(!stall)notFound();
 const event=Array.isArray(stall.events)?stall.events[0]:stall.events;
 const roles=((event?.staffing_roles??[]) as Role[]).filter(role=>role.stall_id===stall.id);
 const fields=[["description","Description"],["products_services","Products / services"],["branding_notes","Branding notes"],["utilities","Utilities"],["equipment","Equipment"],["vendor_details","Vendor details"],["permits_documents","Permits / documents"],["instructions","Instructions"]] as const;
 return <><Link className="button button-secondary mb-4" href="/dashboard/exhibitor/stalls">Back to stalls</Link>{query.saved?<p className="alert mb-4" role="status">Stall details saved.</p>:null}<section className="panel p-6"><span className="badge badge-accent">{event?.verification_status.replaceAll("_"," ")}</span><h1 className="mt-3 text-4xl font-black">{stall.name}</h1><p className="mt-2 text-[var(--muted)]">{event?.title} · {event?.venue}, {event?.city} · {event?.starts_at}–{event?.ends_at}</p>{stall.image_path?<Image className="mt-4 max-h-64 rounded-xl object-cover" src={`/api/media/stall/${stall.id}`} width={800} height={450} alt={`${stall.name} stall`}/>:null}<Link className="button button-primary mt-5" href={`/dashboard/exhibitor/requests/new?stall=${stall.id}`}>Create staffing request</Link></section><form action={updateStallDetails} className="panel mt-5 grid gap-4 p-6"><input type="hidden" name="id" value={stall.id}/><h2 className="text-2xl font-black">Edit stall details</h2><label className="label">Stall name<input className="input" name="name" required defaultValue={stall.name}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="label">Booth number<input className="input" name="booth_number" defaultValue={stall.booth_number??""}/></label><label className="label">Venue location<input className="input" name="booth_location" defaultValue={stall.booth_location??""}/></label><label className="label">Area (sq ft)<input className="input" name="area_sqft" type="number" min="0.01" step="0.01" defaultValue={stall.area_sqft??""}/></label><label className="label">Dimensions<input className="input" name="dimensions" defaultValue={stall.dimensions??""}/></label></div>{fields.map(([name,label])=><label className="label" key={name}>{label}<textarea className="input textarea" name={name} defaultValue={stall[name]??""}/></label>)}<SubmitButton pendingText="Saving…">Save stall</SubmitButton></form><section className="panel mt-5 p-6"><h2 className="text-2xl font-black">Staffing requests</h2><div className="mt-4 grid gap-3">{roles.map(role=><Link className="rounded-xl border border-[var(--line)] p-4" href={`/dashboard/exhibitor/requests/${role.id}`} key={role.id}><strong>{role.title}</strong><p className="text-sm">{role.headcount} needed · {role.status}</p></Link>)}{!roles.length?<p className="text-sm text-[var(--muted)]">No staffing requests for this stall yet.</p>:null}</div></section></>;
}
