import { notFound } from 'next/navigation';
import { DashboardShell } from '@/components/dashboard-shell';
import { EventForm } from '@/components/organizer/forms';
import { organizerContext } from '@/lib/organizer-server';
import { updateSpaceInquiryStatus } from '@/app/actions/space-inquiries';
import { SubmitButton } from '@/components/submit-button';
export default async function EditEvent({params}:{params:Promise<{id:string}>}) {
 const {id}=await params; const {db,company}=await organizerContext();
 const {data:event,error}=await db.from('organizer_events').select('*').eq('id',id).eq('company_id',company!.id).maybeSingle();
 if (error) throw new Error('Unable to load event.'); if (!event) notFound();
 const {data:slots,error:slotsError}=await db.from('event_booking_slots').select('*').eq('event_id',id).order('slot_date').order('start_time');
 const {data:offers,error:offersError}=await db.from('event_space_offers').select('*').eq('event_id',id).eq('is_active',true).order('position');
 if(offersError) throw new Error('Unable to load exhibitor offers.');
 const {data:inquiries,error:inquiriesError}=await db.from('event_space_inquiries').select('id,offer_id,exhibitor_id,requested_area_sqft,requested_units,message,status,created_at').eq('event_id',id).order('created_at',{ascending:false});
 if(inquiriesError) throw new Error('Unable to load exhibitor inquiries.');
 const exhibitorIds=[...new Set((inquiries??[]).map(inquiry=>inquiry.exhibitor_id))];
 const {data:exhibitors}=exhibitorIds.length?await db.from('profiles').select('id,full_name').in('id',exhibitorIds):{data:[]};
 const {data:accounts}=exhibitorIds.length?await db.from('app_accounts').select('id,email').in('id',exhibitorIds):{data:[]};
 if (slotsError) throw new Error('Unable to load booking slots. Apply the booking migration.');
 const slotIds=(slots??[]).map(slot=>slot.id);
 const {data:bookings,error:bookingsError}=slotIds.length?await db.from('event_bookings').select('id,slot_id,guest_name,guest_email,cancelled_at,created_at').in('slot_id',slotIds).order('created_at',{ascending:false}):{data:[],error:null};
 if (bookingsError) throw new Error('Unable to load reservations.');
 return <DashboardShell active="organizer"><div className="max-w-3xl"><h1 className="mb-6 text-4xl font-black">Edit event</h1><EventForm event={event} slots={(slots??[]).filter(slot=>slot.is_active)} offers={offers??[]}/><section className="panel mt-6 p-6"><h2 className="text-2xl font-bold">Exhibitor inquiries</h2><p className="mt-2 text-sm text-[var(--muted)]">Status updates are responses only; they do not reserve a space or collect payment.</p>{inquiries?.length?inquiries.map(inquiry=><div className="border-t border-[var(--line)] py-4" key={inquiry.id}><h3 className="font-bold">{offers?.find(offer=>offer.id===inquiry.offer_id)?.name??'Previously listed offer'} · {inquiry.status}</h3><p className="text-sm">{exhibitors?.find(person=>person.id===inquiry.exhibitor_id)?.full_name??'Exhibitor'} · {accounts?.find(account=>account.id===inquiry.exhibitor_id)?.email??'Email unavailable'}</p><p className="mt-2 text-sm">{inquiry.requested_area_sqft?`${inquiry.requested_area_sqft} sq ft · `:''}{inquiry.requested_units?`${inquiry.requested_units} units`:''}</p><p className="mt-2 whitespace-pre-wrap">{inquiry.message}</p><form action={updateSpaceInquiryStatus} className="mt-3 flex flex-wrap items-end gap-3"><input type="hidden" name="event_id" value={id}/><input type="hidden" name="inquiry_id" value={inquiry.id}/><label className="label">Status<select className="input" name="status" defaultValue={inquiry.status}><option value="new">New</option><option value="contacted">Contacted</option><option value="accepted">Accepted</option><option value="declined">Declined</option></select></label><SubmitButton pendingText="Saving…">Update</SubmitButton></form></div>):<p className="mt-3 text-[var(--muted)]">No exhibitor inquiries yet.</p>}</section><section className="panel mt-6 p-6"><h2 className="text-2xl font-bold">Reservations</h2>{slots?.length?slots.map(slot=><div key={slot.id} className="border-t border-[var(--line)] py-4"><h3 className="font-bold">{slot.slot_date} · {slot.start_time.slice(0,5)}–{slot.end_time.slice(0,5)} · {slot.booked_count}/{slot.capacity} booked{!slot.is_active?' · Closed':''}</h3>{bookings?.filter(booking=>booking.slot_id===slot.id && !booking.cancelled_at).map(booking=><p className="mt-2 text-sm" key={booking.id}>{booking.guest_name} · {booking.guest_email} <form action={async()=>{'use server'; const {cancelOrganizerBooking}=await import('@/app/actions/booking'); await cancelOrganizerBooking(id,booking.id);}} className="inline"><button className="underline" type="submit">Cancel</button></form></p>)}</div>):<p className="mt-3 text-[var(--muted)]">No time slots yet.</p>}</section></div></DashboardShell>;
}
