import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { canTransitionApplication, createShareToken, deriveOperationStatus, filterSharedProfile, hashShareToken, isActiveShare, normalizeEmail, normalizePhone, whatsappUrl } from "../src/lib/agency-operations";
import { parseContactWorkbook } from "../src/lib/agency-import";

test("normalizes contact identifiers and builds WhatsApp links",()=>{assert.equal(normalizePhone("98765 43210"),"+919876543210");assert.equal(normalizeEmail(" Person@Example.COM "),"person@example.com");assert.equal(whatsappUrl("+91 98765 43210","Event update"),"https://wa.me/919876543210?text=Event%20update");assert.equal(normalizePhone("12"),"")});
test("application transitions enforce the pipeline",()=>{assert.equal(canTransitionApplication("applied","shortlisted"),true);assert.equal(canTransitionApplication("approved","assigned"),true);assert.equal(canTransitionApplication("assigned","rejected"),false);assert.equal(canTransitionApplication("completed","closed"),true)});
test("operation status derives from staffing and payment state",()=>{const base={publication:"published",shortlisted:0,pendingClient:0,assigned:0,headcount:3,start:"2099-01-01",end:"2099-01-02"};assert.equal(deriveOperationStatus(base,"2026-01-01"),"staffing_in_progress");assert.equal(deriveOperationStatus({...base,shortlisted:1},"2026-01-01"),"staff_shortlisted");assert.equal(deriveOperationStatus({...base,assigned:3},"2026-01-01"),"staff_confirmed");assert.equal(deriveOperationStatus({...base,settlement:"paid"},"2026-01-01"),"closed")});
test("share tokens are hashed and public profiles are allow-listed",()=>{const {token,hash}=createShareToken();assert.equal(hashShareToken(token),hash);assert.equal(isActiveShare({expires_at:new Date(Date.now()+10000).toISOString()}),true);assert.deepEqual(filterSharedProfile({name:"A",phone:"secret",notes:"never"},["name"]),{name:"A"})});
test("CSV import maps common headings and reports invalid rows",async()=>{const csv=new TextEncoder().encode("Full Name,Mobile,Email ID,Skills\nAnu,9876543210,ANU@example.com,Sales\nMissing,,, ");const rows=await parseContactWorkbook(csv.buffer,"contacts.csv");assert.equal(rows[0].name,"Anu");assert.equal(rows[0].phone,"+919876543210");assert.equal(rows[0].email,"anu@example.com");assert.equal(rows[1].errors.length,1)});
test("agency migration contains privacy, import, and shortlist boundaries",()=>{const migration=fs.readFileSync(new URL("../supabase/migrations/021_agency_portal_operations.sql",import.meta.url),"utf8");assert.match(migration,/create table if not exists public\.client_shortlists/i);assert.match(migration,/token_hash text not null unique/i);assert.match(migration,/agency_contact_import_rows/i);assert.match(migration,/revoke all on public\.agency_client_profiles/i);assert.match(migration,/where a\.talent_id=new\.talent_id[\s\S]*status='assigned'/i)});
