/* eslint-disable @next/next/no-img-element */
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { filterSharedProfile, hashShareToken, isActiveShare } from "@/lib/agency-operations";
import { reviewShortlistMember } from "@/app/actions/client-review";

export default async function ClientReviewPage({params}:{params:Promise<{token:string}>}){
  const {token}=await params,db=await createClient(); if(!db) notFound();
  const {data:share}=await db.from("client_shortlists").select("id,title,expires_at,revoked_at,client_shortlist_members(id,application_id,shared_fields,review_status,client_note,applications(talent_id))").eq("token_hash",hashShareToken(token)).maybeSingle();
  if(!share||!isActiveShare(share)) notFound();
  const members=share.client_shortlist_members??[],talentIds=members.flatMap(member=>{const app=Array.isArray(member.applications)?member.applications[0]:member.applications;return app?.talent_id?[app.talent_id]:[]});
  const {data:profiles}=talentIds.length?await db.from("profiles").select("id,full_name,avatar_url,talent_profiles(skills,languages,availability,experience_years,documents_note),contact_details(phone,alternate_email)").in("id",talentIds):{data:[]}; const profileMap=new Map((profiles??[]).map(profile=>[profile.id,profile]));
  return <main className="page py-10"><header><span className="badge badge-accent">Secure client review</span><h1 className="mt-3 text-4xl font-black">{share.title}</h1><p className="mt-2 text-[var(--muted)]">Review only information approved by the agency. This link expires {new Date(share.expires_at).toLocaleDateString()}.</p></header><div className="mt-8 grid gap-5 md:grid-cols-2">{members.map(member=>{const app=Array.isArray(member.applications)?member.applications[0]:member.applications,profile=app?.talent_id?profileMap.get(app.talent_id):null,talent=Array.isArray(profile?.talent_profiles)?profile.talent_profiles[0]:profile?.talent_profiles,contact=Array.isArray(profile?.contact_details)?profile.contact_details[0]:profile?.contact_details;const safe=filterSharedProfile({photo:profile?.avatar_url?`/api/media/talent/${app?.talent_id}`:null,name:profile?.full_name,skills:talent?.skills,experience:talent?.experience_years,languages:talent?.languages,previous_work:talent?.documents_note,availability:talent?.availability,phone:contact?.phone,email:contact?.alternate_email},member.shared_fields);return <article className="panel p-6" key={member.id}>{safe.photo?<img className="h-24 w-24 rounded-2xl object-cover" src={String(safe.photo)} alt="Approved staff profile"/>:null}<h2 className="mt-4 text-2xl font-black">{String(safe.name??"Staff profile")}</h2>{Object.entries(safe).filter(([key])=>!["photo","name"].includes(key)).map(([key,value])=><p className="mt-2" key={key}><strong className="capitalize">{key.replaceAll("_"," ")}:</strong> {Array.isArray(value)?value.join(", "):String(value??"—")}</p>)}<p className="mt-4"><span className="badge capitalize">{member.review_status.replaceAll("_"," ")}</span></p><form action={reviewShortlistMember} className="mt-4 grid gap-3"><input type="hidden" name="token" value={token}/><input type="hidden" name="member_id" value={member.id}/><label className="label">Client note<textarea className="input textarea" name="note" defaultValue={member.client_note??""}/></label><div className="flex flex-wrap gap-2"><button className="button button-primary" name="status" value="approved">Approve</button><button className="button button-secondary" name="status" value="rejected">Reject</button><button className="button button-secondary" name="status" value="replacement_requested">Request replacement</button></div></form></article>})}</div></main>;
}
