import Link from "next/link";
import { DashboardShell } from "@/components/dashboard-shell";
import { AgencyClientSelector } from "@/components/agency-client-selector";
import { agencyClients, selectedAgencyClient } from "@/lib/agency-workspace";
import { createClient } from "@/lib/supabase/server";
import { publishStaffCall } from "@/app/actions/agency-operations";
import { configureSettlement, markSettlementSent } from "@/app/actions/settlements";

export default async function AgencyRequests({searchParams}:{searchParams:Promise<{client?:string}>}){
  const clients=await agencyClients(),selected=selectedAgencyClient(clients,(await searchParams).client),db=await createClient(); if(!db) throw new Error("Requirements unavailable.");
  const {data,error}=selected?await db.from("events").select("id,title,city,payer_type,staffing_roles(id,title,headcount,status,publication_status,operation_status,work_starts_on,work_ends_on,final_client_charge,agency_share,staffing_settlements(id,status,gross_amount,payer_type))").eq("exhibitor_id",selected.exhibitorId).order("created_at",{ascending:false}):{data:[],error:null};
  if(error) throw new Error("Unable to load requirements."); const roles=(data??[]).flatMap(event=>(event.staffing_roles??[]).map(role=>({...role,event})));
  return <DashboardShell active="agency" current="/dashboard/agency/requests"><h1 className="text-4xl font-black">Staff calls</h1><p className="mt-2 text-[var(--muted)]">Create requirements as drafts, then explicitly publish them to eligible talent.</p><AgencyClientSelector clients={clients} selected={selected} path="/dashboard/agency/requests"/>{selected?<Link className="button button-primary mb-6" href={`/dashboard/agency/requests/new?client=${selected.exhibitorId}`}>New event requirement</Link>:null}<div className="grid gap-4">{roles.map(role=>{const settlement=Array.isArray(role.staffing_settlements)?role.staffing_settlements[0]:role.staffing_settlements;return <article className="panel p-5" key={role.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2"><span className="badge capitalize">{role.publication_status}</span><span className="badge capitalize">{role.operation_status.replaceAll("_"," ")}</span></div><h2 className="mt-3 text-xl font-black">{role.title}</h2><p>{role.event.title} · {role.event.city} · {role.work_starts_on}–{role.work_ends_on}</p><p>{role.headcount} people needed</p></div>{role.publication_status==="draft"?<form action={publishStaffCall}><input type="hidden" name="staffing_role_id" value={role.id}/><button className="button button-primary">Publish staff call</button></form>:null}</div><form action={configureSettlement} className="mt-4 grid gap-3 border-t border-[var(--line)] pt-4 sm:grid-cols-2"><input type="hidden" name="staffing_role_id" value={role.id}/><label className="label">Final client charge<input className="input" name="gross_amount" type="number" min="0" step="0.01" required defaultValue={role.final_client_charge??""}/></label><label className="label">Agency payout<input className="input" name="agency_amount" type="number" min="0" step="0.01" required defaultValue={role.agency_share??0}/></label><button className="button button-secondary sm:col-span-2">Save settlement</button></form>{settlement?.payer_type==="agency"&&["pending","failed"].includes(settlement.status)?<form action={markSettlementSent} className="mt-3 flex flex-wrap items-end gap-3"><input type="hidden" name="settlement_id" value={settlement.id}/><label className="label">Payment reference<input className="input" name="reference"/></label><button className="button button-primary">Mark payment sent</button></form>:null}</article>})}{selected&&!roles.length?<p className="panel p-5">No requirements for this client.</p>:null}</div></DashboardShell>;
}
