import Link from "next/link";

import { ContactImporter } from "@/components/contact-importer";
import { StaffAvailabilityForm } from "@/components/staff-availability-form";
import { saveStaffContact } from "@/app/actions/agency-operations";
import { agencyDataContext } from "@/lib/agency-data";
import { whatsappUrl } from "@/lib/agency-operations";

export default async function StaffPage({searchParams}:{searchParams:Promise<{q?:string;availability?:string;assignment?:string;skill?:string;location?:string}>}) {
  const params=await searchParams,ctx=await agencyDataContext(); if(!ctx) throw new Error("Staff workspace unavailable.");
  const safeQ=(params.q??"").replace(/[,%()]/g,"");
  let query=ctx.db.from("agency_staff_contacts").select("*,recruitment_partners(name)").eq("agency_id",ctx.agency.id).order("updated_at",{ascending:false});
  if(safeQ) query=query.or(`full_name.ilike.%${safeQ}%,phone.ilike.%${safeQ}%,email.ilike.%${safeQ}%`);
  if(params.availability) query=query.eq("availability_status",params.availability);
  if(params.assignment) query=query.eq("assignment_status",params.assignment);
  if(params.location) query=query.ilike("location",`%${params.location}%`);
  if(params.skill) query=query.contains("skills",[params.skill]);
  const [{data:staff},{data:partners}]=await Promise.all([query,ctx.db.from("recruitment_partners").select("id,name").eq("agency_id",ctx.agency.id).eq("status","active")]);
  return <>
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-black">Staff</h1><p className="mt-2 text-[var(--muted)]">Search, match, contact, and update availability without opening each profile.</p></div><Link className="button button-secondary" href="#import">Import CSV or Excel</Link></div>
    <form className="panel mt-6 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-5"><input className="input" name="q" placeholder="Name, phone, email" defaultValue={params.q}/><select className="input" name="availability" defaultValue={params.availability??""}><option value="">Any availability</option><option value="available">Available</option><option value="partially_available">Partially available</option><option value="unavailable">Unavailable</option></select><select className="input" name="assignment" defaultValue={params.assignment??""}><option value="">Any assignment</option><option value="unassigned">Unassigned</option><option value="assigned">Assigned</option><option value="on_assignment">On assignment</option><option value="inactive">Inactive</option></select><input className="input" name="location" placeholder="Location" defaultValue={params.location}/><button className="button button-primary">Filter staff</button></form>
    <details className="panel mt-6 p-6"><summary className="cursor-pointer text-xl font-black">Add staff manually</summary><form action={saveStaffContact} className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><label className="label">Full name<input className="input" name="full_name" required/></label><label className="label">Phone<input className="input" name="phone" type="tel"/></label><label className="label">Email<input className="input" name="email" type="email"/></label><label className="label">WhatsApp<input className="input" name="whatsapp_phone" type="tel"/></label><label className="label">Location<input className="input" name="location"/></label><label className="label">Gender<input className="input" name="gender"/></label><label className="label">Experience years<input className="input" name="experience_years" min="0" step="0.5" type="number"/></label><label className="label">Skills<input className="input" name="skills"/></label><label className="label">Languages<input className="input" name="languages"/></label><label className="label">Recruitment partner<select className="input" name="recruiter_partner_id"><option value="">Direct staff</option>{partners?.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label className="label sm:col-span-2">Work history<textarea className="input textarea" name="work_history"/></label><button className="button button-primary sm:col-span-2 xl:col-span-3">Save staff profile</button></form></details>
    <div className="mt-6 grid gap-4 lg:grid-cols-2">{staff?.map(person=>{const wa=whatsappUrl(person.whatsapp_phone||person.phone||"");return <article className="panel p-5" key={person.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className="badge capitalize">{person.availability_status.replaceAll("_"," ")}</span><span className="badge capitalize">{person.assignment_status.replaceAll("_"," ")}</span></div><Link href={`/dashboard/agency/staff/${person.id}`}><h2 className="mt-3 text-xl font-black">{person.full_name}</h2></Link><p className="text-sm text-[var(--muted)]">{person.location||"Location not added"} · {person.skills?.join(", ")||"No skills"}</p></div><StaffAvailabilityForm id={person.id} status={person.availability_status}/></div><div className="mt-4 flex flex-wrap gap-2">{person.phone?<a className="button button-secondary" href={`tel:${person.phone}`}>Call</a>:null}{wa?<a className="button button-secondary" href={wa} target="_blank" rel="noreferrer">WhatsApp</a>:null}{person.email?<a className="button button-secondary" href={`mailto:${person.email}`}>Email</a>:null}<Link className="button button-primary" href={`/dashboard/agency/staff/${person.id}`}>Open profile</Link></div></article>})}{!staff?.length?<p className="panel p-5">No matching staff profiles.</p>:null}</div>
    <div className="mt-8" id="import"><ContactImporter/></div>
  </>;
}
