"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { applicationPipeline, canTransitionApplication, createShareToken, normalizeEmail, normalizePhone } from "@/lib/agency-operations";
import type { ApplicationStatus, OperationStatus, StaffAvailabilityStatus } from "@/lib/types";

async function context(){const profile=await requireRole(["agency"]);const db=await createClient();if(!db)throw new Error("Agency workspace unavailable.");const {data:agency}=await db.from("agencies").select("id").eq("owner_id",profile.id).maybeSingle();if(!agency)throw new Error("Complete the agency profile first.");return {profile,db,agency};}
const split=(value:FormDataEntryValue|null)=>String(value??"").split(",").map(x=>x.trim()).filter(Boolean);
const text=(data:FormData,key:string,max=5000)=>String(data.get(key)??"").trim().slice(0,max);

export async function saveStaffContact(formData:FormData){const {db,agency}=await context();const id=text(formData,"id",100),full_name=text(formData,"full_name",160),phone=normalizePhone(text(formData,"phone",40)),email=normalizeEmail(text(formData,"email",254)),whatsapp_phone=normalizePhone(text(formData,"whatsapp_phone",40));if(!full_name||(!phone&&!email))throw new Error("Enter a name and a valid phone or email.");const values={agency_id:agency.id,full_name,phone:phone||null,email:email||null,normalized_phone:phone||null,normalized_email:email||null,whatsapp_phone:whatsapp_phone||null,location:text(formData,"location",160)||null,gender:text(formData,"gender",40)||null,date_of_birth:text(formData,"date_of_birth",10)||null,languages:split(formData.get("languages")),skills:split(formData.get("skills")),experience_years:Math.max(0,Number(formData.get("experience_years")||0)),work_history:text(formData,"work_history")||null,availability:text(formData,"availability",160)||null,availability_status:text(formData,"availability_status",40)||"available",assignment_status:text(formData,"assignment_status",40)||"unassigned",recruiter_partner_id:text(formData,"recruiter_partner_id",100)||null,notes:text(formData,"notes")||null,updated_at:new Date().toISOString()};const result=id?await db.from("agency_staff_contacts").update(values).eq("id",id).eq("agency_id",agency.id):await db.from("agency_staff_contacts").insert(values);if(result.error)throw new Error("Unable to save this staff profile.");revalidatePath("/dashboard/agency/staff");}

export async function setStaffAvailability(formData:FormData){const {db,agency}=await context();const id=text(formData,"id",100),status=text(formData,"availability_status",40) as StaffAvailabilityStatus;if(!["available","partially_available","unavailable"].includes(status))throw new Error("Choose a valid availability status.");const {data}=await db.from("agency_staff_contacts").update({availability_status:status,updated_at:new Date().toISOString()}).eq("id",id).eq("agency_id",agency.id).select("id").maybeSingle();if(!data)throw new Error("Staff profile not found.");revalidatePath("/dashboard/agency/staff");}

export async function inviteStaffContact(formData:FormData){const {db,agency,profile}=await context();const id=text(formData,"id",100);const {data}=await db.from("agency_staff_contacts").update({invited_at:new Date().toISOString()}).eq("id",id).eq("agency_id",agency.id).is("talent_id",null).select("id,email,phone").maybeSingle();if(!data)throw new Error("Unclaimed staff profile not found.");await db.from("agency_staff_invites").update({revoked_at:new Date().toISOString()}).eq("staff_contact_id",id).is("claimed_at",null).is("revoked_at",null);const {token,hash}=createShareToken();await db.from("agency_staff_invites").insert({agency_id:agency.id,staff_contact_id:id,token_hash:hash,expires_at:new Date(Date.now()+7*86400000).toISOString(),created_by:profile.id});await db.from("agency_notifications").insert({agency_id:agency.id,title:"Staff invitation prepared",body:`Invitation prepared for ${data.email||data.phone}.`,href:`/dashboard/agency/staff/${id}`});redirect(`/staff-invite/${encodeURIComponent(token)}`);}

export async function saveRecruitmentPartner(formData:FormData){const {db,agency}=await context();const name=text(formData,"name",160);if(!name)throw new Error("Partner name is required.");const {error}=await db.from("recruitment_partners").insert({agency_id:agency.id,name,contact_person:text(formData,"contact_person",160)||null,phone:normalizePhone(text(formData,"phone",40))||null,email:normalizeEmail(text(formData,"email",254))||null,location:text(formData,"location",160)||null,staff_count:Math.max(0,Number(formData.get("staff_count")||0)),skills:split(formData.get("skills")),previous_work:text(formData,"previous_work")||null,payment_information:text(formData,"payment_information")||null});if(error)throw new Error("Unable to add recruitment partner.");revalidatePath("/dashboard/agency/partners");}

export async function updateOperationStatus(formData:FormData){const {db,agency,profile}=await context();const id=text(formData,"staffing_role_id",100),to=text(formData,"status",60) as OperationStatus;const allowed=["requirement_received","staffing_in_progress","staff_shortlisted","client_approval_pending","staff_confirmed","event_ongoing","event_completed","payment_pending","closed"];if(!allowed.includes(to))throw new Error("Choose a valid operation status.");const {data:role}=await db.from("staffing_roles").select("operation_status,events(agency_id)").eq("id",id).maybeSingle();const event=Array.isArray(role?.events)?role.events[0]:role?.events;if(!role||event?.agency_id!==agency.id)throw new Error("Operation not found.");await db.from("staffing_roles").update({operation_status:to}).eq("id",id);await db.from("operation_status_history").insert({staffing_role_id:id,from_status:role.operation_status,to_status:to,changed_by:profile.id,note:text(formData,"note",500)||null});revalidatePath("/dashboard/agency/operations");}

export async function publishStaffCall(formData:FormData){const {db,agency}=await context();const id=text(formData,"staffing_role_id",100);const {data}=await db.from("staffing_roles").select("id,events!inner(agency_id)").eq("id",id).eq("events.agency_id",agency.id).maybeSingle();if(!data)throw new Error("Staffing requirement not found.");await db.from("staffing_roles").update({publication_status:"published",published_at:new Date().toISOString(),operation_status:"staffing_in_progress",status:"open"}).eq("id",id);revalidatePath("/dashboard/agency/requests");revalidatePath("/browse");}

export async function requestStaffInformation(formData:FormData){const {db,agency,profile}=await context();const requested=split(formData.get("requested_types"));if(!requested.length)throw new Error("Choose at least one requested item.");const applicationId=text(formData,"application_id",100);const {data:application}=await db.from("applications").select("id,staffing_roles(events(agency_id))").eq("id",applicationId).maybeSingle();const role=Array.isArray(application?.staffing_roles)?application.staffing_roles[0]:application?.staffing_roles;const event=Array.isArray(role?.events)?role.events[0]:role?.events;if(!application||event?.agency_id!==agency.id)throw new Error("Application not found.");await db.from("staff_information_requests").insert({agency_id:agency.id,application_id:applicationId,requested_types:requested,message:text(formData,"message",1000)||null,requested_by:profile.id});await db.from("applications").update({status:"documents_requested",updated_at:new Date().toISOString()}).eq("id",applicationId);revalidatePath("/dashboard/agency/applicants");}

export async function updateAgencyApplication(formData:FormData){const {db,agency}=await context();const id=text(formData,"application_id",100),to=text(formData,"status",40) as ApplicationStatus;if(!applicationPipeline.includes(to))throw new Error("Choose a valid status.");const {data:app}=await db.from("applications").select("status,staffing_roles(events(agency_id))").eq("id",id).maybeSingle();const role=Array.isArray(app?.staffing_roles)?app.staffing_roles[0]:app?.staffing_roles;const event=Array.isArray(role?.events)?role.events[0]:role?.events;if(!app||event?.agency_id!==agency.id||!canTransitionApplication(app.status as ApplicationStatus,to))throw new Error("That application transition is not allowed.");const {error}=await db.from("applications").update({status:to,updated_at:new Date().toISOString()}).eq("id",id);if(error?.message.includes("Role is full"))throw new Error("This requirement has no remaining openings.");if(error)throw new Error("Unable to update the application.");revalidatePath("/dashboard/agency/applicants");revalidatePath("/dashboard/agency/operations");}

export async function createClientShortlist(formData:FormData){const {db,agency,profile}=await context();const staffingRoleId=text(formData,"staffing_role_id",100),exhibitorId=text(formData,"exhibitor_id",100),applicationIds=[...new Set(formData.getAll("application_id").map(String))],fields=formData.getAll("shared_field").map(String);if(!applicationIds.length||!fields.includes("name"))throw new Error("Select applicants and at least the name field.");const {data:role}=await db.from("staffing_roles").select("id,title,events(agency_id,exhibitor_id)").eq("id",staffingRoleId).maybeSingle();const event=Array.isArray(role?.events)?role.events[0]:role?.events;if(!role||event?.agency_id!==agency.id||event?.exhibitor_id!==exhibitorId)throw new Error("Staffing requirement not found.");const {data:ownedApplications}=await db.from("applications").select("id").eq("staffing_role_id",staffingRoleId).in("id",applicationIds);if((ownedApplications??[]).length!==applicationIds.length)throw new Error("One or more selected applications are invalid.");const {token,hash}=createShareToken(),expiresAt=new Date(Date.now()+7*86400000).toISOString();const {data:shortlist,error}=await db.from("client_shortlists").insert({agency_id:agency.id,exhibitor_id:exhibitorId,staffing_role_id:staffingRoleId,title:`${role.title} shortlist`,token_hash:hash,expires_at:expiresAt,created_by:profile.id}).select("id").single();if(error||!shortlist)throw new Error("Unable to create shortlist.");await db.from("client_shortlist_members").insert(applicationIds.map(application_id=>({shortlist_id:shortlist.id,application_id,shared_fields:fields})));await db.from("staffing_roles").update({operation_status:"client_approval_pending"}).eq("id",staffingRoleId);redirect(`/dashboard/agency/applicants?share=${encodeURIComponent(token)}`);}
